const LandObj = {
  en_US: {
    please_enter_account: "Please enter a username. ",
    please_enter_pwd: "Please enter a password.",
    please_enter_full_name: "Please enter your full name.",
    please_enter_email: "Please enter your email address.",
    please_enter_access_code: "Please enter an access code.",
    login: "Connect Now",
    accesscode: "Access Code",
    password: "Password",
    account: "Account",
    full_name: "Full Name",
    email: "Email",
    or: "or",
    one_click_login: "One-click Login",
    account_login: "Account Login",
    voucher_login: "Voucher Login",
  },
  zh_CN: {
    please_enter_account: "请输入用户名。",
    please_enter_pwd: "请输入密码。",
    please_enter_full_name: "请输入您的全名。",
    please_enter_email: "请输入您的电子邮件地址。",
    please_enter_access_code: "请输入访问代码。",
    login: "立即连接",
    accesscode: "访问代码",
    password: "密码",
    account: "账户",
    full_name: "全名",
    email: "电子邮件",
    or: "或",
    one_click_login: "一键登录",
    account_login: "账户登录",
    voucher_login: "优惠券登录",
  },
  es_ES: {
    please_enter_account: "Introduzca el nombre de usuario.",
    please_enter_pwd: "Introduzca la contraseña.",
    please_enter_full_name: "Introduzca su nombre completo.",
    please_enter_email: "Introduzca su correo electrónico.",
    please_enter_access_code: "Por favor ingrese el código de acceso.",
    login: "Iniciar sesión",
    accesscode: "Código de acceso",
    password: "Contraseña",
    account: "Cuenta",
    full_name: "Nombre completo",
    email: "Correo electrónico",
    or: "o",
    one_click_login: "Inicio de sesión con un clic",
    account_login: "Inicio de sesión con cuenta",
    voucher_login: "Inicio de sesión con cupón",
  },
};
